### ISSUE TITLE
storage: Expose "Metadata" in Reader

### ISSUE THREAD

**Issue by vangent** [GoogleCloudPlatform/google-cloud-go#1132]
This request is similar to #1091.

The key/value "metadata" is carried in the [ObjectAttrs](https://godoc.org/cloud.google.com/go/storage#ObjectAttrs.Metadata) in the API. It would be helpful to also expose them in [Reader](https://godoc.org/cloud.google.com/go/storage#Reader) so that the user doesn't need to make a separate call to get them.

I've confirmed that the metadata is returned as HTTP headers in the response to the GET request that Object.NewRangeReader makes, e.g.:

```
      X-Goog-Meta-Key-A:
      - value-a
      X-Goog-Meta-Key-B:
      - value-b
      X-Goog-Meta-Key-C:
      - vAlUe-c

```

More generally, could Reader return an ObjectAttrs? I haven't looked through all the fields to see if they are all accessible.
