### ISSUE TITLE
pubsub client does not work inside a docker container

### ISSUE THREAD

**Issue by marwan-at-work** [GoogleCloudPlatform/google-cloud-go#791]
I have this compose file

```
version: "3.3"
services:
  dev:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    ports:
      - '3000:3000'
    environment:
      - PUBSUB_EMULATOR_HOST=http://pubsub:8085
      - PUBSUB_PROJECT_ID=marwan-test
    depends_on:
      - pubsub
  pubsub:
    image: google/cloud-sdk
    ports:
      - '8085:8085'
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port", "0.0.0.0:8085"]
```

My `dev` container is a `golang:1.9.1` image with the following `main.go` file: 

```go
func main()
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
	defer cancel()

	cl, err := pubsub.NewClient(ctx, "marwan-test")
	if err != nil {
                panic(err)
	}

	t, err := cl.CreateTopic(ctx, "email")
	if err != nil {
		panic(err) // if this program is running inside a docker image, it will panic, otherwise -- create topic succeeds.
	}
}
```

if the above file is running inside a container, then `cl.CreateTopic` will be stuck indefinitely until context is timed out. However, if I run this file from the host machine and just connect to `localhost:8085` instead of `pubsub:8085` -- then it works. 

I tried debugging why `CreateTopic` gets stuck infinitely, and it seems that grpc.Dial is settings its client connection to `TRANSIENT_FAILURE`.
